version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: kudinov/yamdb_final:latest
    restart: always
    volumes:
      - static_volume:/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/code/static
      - media:/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web